### ISSUE TITLE
maxValue is always 100 if not 0

### ISSUE THREAD

**Issue by nathanielajayi7** [Nulllix/simple_circular_progress_bar#7]
ProgressBar is 100 always if given non zero maxValue

**Comment by Nulllix** [comment]
Hi! Sorry for the long wait. I can't reproduce a problem like this in myself, could you please drop a code example?

For example, I set the maxValue to 9:
![Alt Text](https://media.giphy.com/media/njT4r17ZYZ91RAdzmv/giphy.gif)

**Comment by nathanielajayi7** [comment]
![Screenshot_20220703-171048.png](https://user-images.githubusercontent.com/54505255/177048007-9cd72ea4-ed64-4da4-b823-482e230d4800.png)

The default maxValue is 100 not 10. So, I thought adding a value <100 should produce an arc instead of a full circle.

Consider throwing an error when there's an invalid range input for progress?

**Comment by Nulllix** [comment]
> The default maxValue is 100 not 10. So, I thought adding a value <100 should produce an arc instead of a full circle.

Sorry, arc creation is not currently supported, I will try to add this soon (everything I'm going to add is listed here: #5).

> Consider throwing an error when there's an invalid range input for progress?

It seems to me that it would be more correct to avoid an application error/failure if an invalid value is entered. But you're right, maybe for debug i should add something to report the error. I'll add that to my roadmap.

Can I close the issues?

**Comment by Nulllix** [comment]
I'm closing the issue because I think the problem is solved and there have been no new comments for a week.
